# version: "3"

# services:
#   app:
#     build: .
#     command: npm start
#     ports:
#       - "3000:3000"
#     volumes:
#       - .:/usr/app



# version: "3.8"

# services:
#   mysql:
#     image: mysql:5.7
#     container_name: pipego-mysql
#     restart: unless-stopped
#     env_file: ./.env
#     # environment:
#     #   - name=value
#     ports:
#       - "3306:3007"
#     expose:
#       - 1234
#     healthcheck:
#       test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
#       timeout: 30s
#       retries: 10

#   app:
#      depends_on:
#         mysql:
#           condition: service_healthy
#         build:
#           context: ./
#           dockerfile: Dockerfile
#           working_dir: /usr/app
#           env_file: ./.env
#           # environment:
#           # - name=value
#           ports: 
#           - "3001:3000"

services:
  mysql:
    image: mysql:5.7
    container_name: pipego-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3308:3006"
    expose:
      - 1234
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      retries: 10

  app:
    depends_on:
      - mysql
    build:
      context: ./
      dockerfile: Dockerfile
    working_dir: /usr/app
    ports:
      - "3001:3000"

