services:
  mysql:
    image: mysql:5.7
    container_name: pipego-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3308:3006"
    expose:
      - 1234
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      retries: 10

  app:
    depends_on:
      - mysql
    build:
      context: ./
      dockerfile: Dockerfile
    working_dir: /usr/app
    ports:
      - "3001:3000"

